### PR TITLE
Not using abs

### PR DESCRIPTION
**Pull request by danielczinege**
Snad jsem udělal správně ten pull request.
Dokončil jsem checkery na "not using abs in condition" a "redundant compare in condition".
Kontroluju tam i věci jako "x > 4 or x < 8" a dávám, že se to dá nahradit True, případně podobné s "and", které je vždy False.
A ještě když je "x < 6 or x >6" jako "x != 6". Nebo "x >=6 and x <= 6" jako "x == 6".

Příští týden bych chtěl dodělat i "not using max in condition with variables", když ho budu dělat, tak můžu pokračovat na této branchi nebo si mám vytvořit novou?

### CODE REVIEW

**Comment by GiraffeReversed** [comment]
I'll take a look at it sometime next week (if all goes well). Meanwhile, if you want to start working on a new detector, start a new branch on top of duplication-antiunify. I will probably make some changes to this branch before merging them.

**Comment by danielczinege** [comment]
I have just noticed that the tests for redundant compare were not finished. Don't know how that happened, but now they should be complete.

**Comment by GiraffeReversed** [comment]
I have decided to move the checkers to SimplifiableIf (the detectors deal with simplifiable conditions, which is close enough, and there are many short problems as it is).

I also changed the base branch from main to development. When you create a new branch, start from development (not duplication-aunify, as I previously asked; sorry for the inconsistent instructions, I am still figuring out how best to do this :)).

I renamed the type aliases to follow naming conventions (CamelCase) and somewhat compressed the tests.

I am currently running tests on my larger dataset to see if the new detectors throw some exception somewhere. Once they are finished, I will take a look at the results and let you know.

**Comment by GiraffeReversed** [comment]
An I was wondering: could precision of `_is_number` be improved by using `get_const_value`? (it evaluates even more complicated expressions than -5) Or could it introduce some false positives?

**Comment by GiraffeReversed** [comment]
The results look pretty good :) Simplifiable with abs even managed to correctly suggest `'float(y[1]) > 90 or float(y[1]) < -90 or float(y[1]) > 180 or float(y[1]) < -180' can be replaced with 'abs(float(y[1])) > 90'`.

I suggest separating "compare instead of equal" from "redundant compare in condition" (I added them to the defect table, together with feedback I suggest to use). I think that each of the cases deserves slightly different feedback and each has slightly different severity (and selecting which of the cases should be reported requires them to have different ids).

Would it be complicated to change feedback for redundant-compare-avoidable-with-max-min so that it would respect order from the first part of the condition? (i.e. instead of `'alice >= k and bob >= k' can be replaced with 'k <= min(alice, bob)'` suggest `'alice >= k and bob >= k'`) Should it take more than a quarter of an hour, then leave it as it is.

**Comment by danielczinege** [comment]
> An I was wondering: could precision of `_is_number` be improved by using `get_const_value`? (it evaluates even more complicated expressions than -5) Or could it introduce some false positives?

At first I used the `get_const_value` in the `_is_number` method, but that produced some errors, because `_get_node_comparator_const_value` method calls `_is_number` on left and right children of a comparator. And that produced errors in for example a file: `data/umime_classic/50/60/36763423-2022-05-27_13:45:15.py`, here is the code from the file that produced error: `(a>b and a%2==0) or (b>a and b%2==0) == True` the problem was that that the left children of the rightmost `==` was a `or` operation that had `and` operations as its children and that was the problem. And I believe that there would be probably more problems like this, so maybe I could write my own function for that. Do you think that I should do that or is it not worth the time?

**Comment by GiraffeReversed** [comment]
Ok, I fixed `get_const_value` and reimplemented `_is_number` to use it (btw, you can use `isinstance(v, tuple)`) to check if the value is an instance of any of the types in the tuple.

**Comment by danielczinege** [comment]
> I suggest separating "compare instead of equal" from "redundant compare in condition" (I added them to the defect table, together with feedback I suggest to use). I think that each of the cases deserves slightly different feedback and each has slightly different severity (and selecting which of the cases should be reported requires them to have different ids).
> 

I have separated them, but I didn't quite understand the feedback you suggest to use, particularly this one `'%s' can be simplified to '%s', change it if it is on purpose`. I think it should be `'%s' can be simplified to '%s', change it if it is not on purpose` or possibly `'%s' can be simplified to '%s', don't change it if it is on purpose`, am I right?

**Comment by danielczinege** [comment]
> Would it be complicated to change feedback for redundant-compare-avoidable-with-max-min so that it would respect order from the first part of the condition? (i.e. instead of `'alice >= k and bob >= k' can be replaced with 'k <= min(alice, bob)'` suggest `'alice >= k and bob >= k'`) Should it take more than a quarter of an hour, then leave it as it is.

I will take a look on this right now. I suppose you meant: "(i.e. instead of `'alice >= k and bob >= k' can be replaced with 'k <= min(alice, bob)'` suggest `'min(alice, bob) >= k'`)"?

**Comment by danielczinege** [comment]
This took much longer than I expected, but I have changed it so that only if all operands have the expression that does not go into max/min on one side of the comparison, then I respect the order. Otherwise I suggest it so that the comparison is either `<` or `<=`.

**Comment by danielczinege** [comment]
I have moved the code from branch simplifiable-test-by-equals here, as we discussed in the email.

**Comment by danielczinege** [comment]
Checker "simplifiable-test-by-equals" is now finished.
It can suggest changes for expressions like x % 2 == 0 and y % 2 == 0 or x % 2 == 1 and y % 2 == 1, where the modulo can be any integer and x/y can be any pure expression. It can find out whether the entire expression is always True or some part can be simplified to x % 2 == y % 2 or inequality.

**Comment by GiraffeReversed** [comment]
I have made some last minor changes (bugfix and wording change) and I have merged the request (and deleted both now-obsolete branches). If you start working on a new checker, start from `development`.

**Pull request merged**
