### PR TITLE
Redundant condition part

### PR DESCRIPTION
**Pull request by danielczinege**
Checker pro detekci chyb typu:
```x == 0 or x % 2 == 0```
nebo
```
def winner(a, b):
    if abs(a-b)<50 and abs(a-b) != 0:
        if a-b > 0:
            print("B")
        else:
            print("A")
    elif a == b:
        print("AB")
    else:
        if a-b>0:
            print("A")
        else:
            print("B")
```

### CODE REVIEW

**Comment by GiraffeReversed** [comment]
Detector `redundant-condition-part` fails on `hour_format = (hours % 12) or 12` (gives feedback `'hours % 12 or 12' can be replaced with '12'`, which is not true).

In general, it is unclear whether this type of advice should be given, because the value after or can be of different type.

**Comment by danielczinege** [comment]
I have changed the format of suggestions for redundant-condition-part-in-if, as we discussed. I have split the redundant-condition-part-in-if checker into: redundant-condition-in-if, using-elif-instead-of-else, redundant-condition-part-in-if, redundant-condition-part-in-if-reorder. It is a little more than what you wanted, but I think that the redundant-condition-in-if and using-elif-instead-of-else are better to be separated.

I also changed the redundant condition part to skip the expressions containing operands that could be of a different type than boolean. And also expressions where some operand is either True, or False. (like x == 0 or False)

**Comment by danielczinege** [comment]
I have addressed all the things we talked about in our emails.

**Comment by GiraffeReversed** [comment]
I have found some erroneous cases and some cases when `condition-always-true-in-elif` misses cases reported by `redundant-elif`. I added tests for these cases.

**Comment by danielczinege** [comment]
> I have found some erroneous cases and some cases when `condition-always-true-in-elif` misses cases reported by `redundant-elif`. I added tests for these cases.

Thank you for catching these. :) There were a few problems; I forgot to add a test for pureness to visit_compare.
I also initially thought that guess_type() could not 'guess' the type of function call or binary operations, so I was doing this part on my end, and this led to some issues. But I started using guess_type() even for the 'm%n' cases and such now.

While doing this change, though, I noticed a few issues with `guess_type()`:
   - it seems to assume that the result of max/min is always a number, but in Python, you can do max/min on strings as well.
   - it also seems to assume that % always returns an integer; for example, in `(m ** (1/2)) % n`, guess_type() returns that it is an integer, but it does not have to be.

And the other issues where caused by incomplete list of pure nodes, I added Slice, List, Set, Dict and Tuple to be pure and added isinstance() to be considered pure function as well.

**Comment by GiraffeReversed** [comment]
I have merged the other PR and now there are some merge requests. Could you rebase this branch on development and solve them? But if you have any issues, let me know :)

Specifically, please consolidate SimplifiableIf._is_pure_expression and utils.is_pure_expression as the utils function. Also, containers (such as List) are not necessarily pure, if some element is a call to an impure function.

Also, I noticed method `_is_elif_branch`, which seems to do the same thing as `utils.is_parents_elif`.

> it seems to assume that the result of max/min is always a number, but in Python, you can do max/min on strings as well.

Fixed on development. Not sure what I was thinking there :D

> it also seems to assume that % always returns an integer; for example, in (m ** (1/2)) % n, guess_type() returns that it is an integer, but it does not have to be.

Well, not always, but maybe a bit too often. Fixed on development.

**Comment by danielczinege** [comment]
The rebase is done.

> Specifically, please consolidate SimplifiableIf._is_pure_expression and utils.is_pure_expression as the utils function. Also, containers (such as List) are not necessarily pure, if some element is a call to an impure function.
>
The current implementation of `is_pure_expression()` should handle containers as intended, since it recursively checks the purity of children nodes. While the helper function `_is_pure_node` might have a slightly misleading name, it serves only to filter the node types at the top level. I have added `_` (underscore) before the `_is_pure_node` name to indicate that it is just a helper function.

> Also, I noticed method `_is_elif_branch`, which seems to do the same thing as `utils.is_parents_elif`.
> 
I have replaced the implementation of `utils.is_parents_elif` with my `_is_elif_branch` since it really does the same thing. The only thing that it does additionally is that it checks whether the parent is not None (this can happen). And there was a slight difference, my used `is` and yours used `==`, but I think that `is` is more correct since we want to check for the exact same object?

I wanted to let you know that I had to comment out one test case, as the updated implementation of `guess_type()` currently cannot infer the type of `m % n`, even when both `m` and `n` are initialized as numbers. It is not a mistake, but I just wanted to let you know, that there is a room for future improvement. :)

**Comment by danielczinege** [comment]
> The rebase is done.
> 
> > Specifically, please consolidate SimplifiableIf._is_pure_expression and utils.is_pure_expression as the utils function. Also, containers (such as List) are not necessarily pure, if some element is a call to an impure function.
> 
> The current implementation of is_pure_expression() should handle containers as intended, since it recursively checks the purity of children nodes. While the helper function `_is_pure_node` might have a slightly misleading name, it serves only to filter the node types at the top level. I have added `_` (underscore) before the _is_pure_node name to indicate that it is just a helper function.
> 
> > Also, I noticed method `_is_elif_branch`, which seems to do the same thing as `utils.is_parents_elif`.
> 
> I have replaced the implementation of `utils.is_parents_elif` with my `_is_elif_branch` since it really does the same thing. The only thing that it does additionally is that it checks whether the parent is not None (this can happen). And there was a slight difference, my used 'is' and yours used '==', but I think that 'is' is more correct since we want to check for the exact same object?
> 
> I wanted to let you know that I had to comment out one test case, as the updated implementation of guess_type() currently cannot infer the type of m % n, even when both m and n are initialized as numbers. It is not a mistake, but I just wanted to let you know, that there is still room for improvement. :)

**Comment by danielczinege** [comment]
> The rebase is done.
> Specifically, please consolidate SimplifiableIf._is_pure_expression and utils.is_pure_expression as the utils function. Also, containers (such as List) are not necessarily pure, if some element is a call to an impure function.
> > 
> > 
> > The current implementation of is_pure_expression() should handle containers as intended, since it recursively checks the purity of children nodes. While the helper function `_is_pure_node` might have a slightly misleading name, it serves only to filter the node types at the top level. I have added `_` (underscore) before the _is_pure_node name to indicate that it is just a helper function.
> > > Also, I noticed method `_is_elif_branch`, which seems to do the same thing as `utils.is_parents_elif`.
> > 
> > 
> > I have replaced the implementation of `utils.is_parents_elif` with my `_is_elif_branch` since it really does the same thing. The only thing that it does additionally is that it checks whether the parent is not None (this can happen). And there was a slight difference, my used 'is' and yours used '==', but I think that 'is' is more correct since we want to check for the exact same object?
> > I wanted to let you know that I had to comment out one test case, as the updated implementation of guess_type() currently cannot infer the type of m % n, even when both m and n are initialized as numbers. It is not a mistake, but I just wanted to let you know, that there is still room for improvement. :)

**Comment by danielczinege** [comment]
Don't know how I did it but I accidentallly closed the PR. :(

**Comment by GiraffeReversed** [comment]
All looks good now, thanks for all the changes.

> The current implementation of is_pure_expression() should handle containers as intended, since it recursively checks the purity of children nodes. While the helper function _is_pure_node might have a slightly misleading name, it serves only to filter the node types at the top level.

Yes, you are right of course :)

> I wanted to let you know that I had to comment out one test case, as the updated implementation of guess_type() currently cannot infer the type of m % n, even when both m and n are initialized as numbers. It is not a mistake, but I just wanted to let you know, that there is a room for future improvement. :)

There is still a lot of room for improvement there, but thanks for letting me know about this issue.

**Pull request merged**
